# Generated by Django 5.1.7 on 2025-05-07 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('gali', 'Gali'), ('faridabad', 'Faridabad'), ('gurgaon', 'Gurgaon'), ('disawer', 'Disawer'), ('gaziabad', 'Gaziabad')], max_length=20)),
                ('bet_type', models.CharField(choices=[('single', '1 to 100'), ('andar', 'Andar 0-9'), ('bahar', 'Bahar 0-9')], max_length=10)),
                ('number', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
