# Generated by Django 5.1.7 on 2025-05-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={},
        ),
        migrations.RemoveField(
            model_name='bet',
            name='bet_type',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='game',
        ),
        migrations.AddField(
            model_name='bet',
            name='category',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Andar', 'Andar'), ('Bahar', 'Bahar')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='game_type',
            field=models.CharField(choices=[('Gali', 'Gali'), ('Faridabad', 'Faridabad'), ('Gurgaon', 'Gurgaon'), ('Disawer', 'Disawer'), ('Gaziabad', 'Gaziabad')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='payout_multiplier',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
