# Generated by Django 5.1.7 on 2025-05-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_bet_options_remove_bet_bet_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bet',
        ),
    ]
